# Generated by Django 3.2.6 on 2021-09-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0002_auto_20210904_2114'),
        ('distributor', '0002_legislations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Legislations',
            new_name='Legislation',
        ),
        migrations.CreateModel(
            name='LegislationPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdf')),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.legislation')),
            ],
        ),
    ]
