# Generated by Django 3.2.6 on 2021-08-09 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=None)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor.category')),
                ('tags', models.ManyToManyField(to='distributor.Tag')),
            ],
        ),
    ]
