# Generated by Django 3.2.6 on 2021-08-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0004_auto_20210818_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor.category'),
        ),
    ]
