# Generated by Django 3.2.5 on 2021-08-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='distributor.brandcar'),
        ),
    ]
