# Generated by Django 3.2.6 on 2021-09-05 18:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_auto_20210906_0005'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favourites', '0002_auto_20210904_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteLegislations',
            new_name='FavouriteLegislation',
        ),
        migrations.RenameField(
            model_name='favouritelegislation',
            old_name='legislations',
            new_name='legislation',
        ),
    ]
